### ISSUE TITLE
Plugin no longer works on macOS 10.14

### ISSUE THREAD

**Issue by quentinmit** [fredemmott/StreamDeck-AudioSwitcher#84]
**Describe the bug**
After the update on 8/1, the plugin no longer works on macOS 10.14. (Note that Stream Deck itself supports [macOS 10.11+](https://help.elgato.com/hc/en-us/articles/360027959372-Elgato-Stream-Deck-Technical-Specifications).)

I tried building the source so that I could try to track the problem down myself, and I discovered that the source doesn't even build on 10.14:

```
In file included from /Users/quentin/Software/StreamDeck-AudioSwitcher/build/_deps/streamdecksdk-src/StreamDeckSDK/ESDUtilities.cpp:5:
/Users/quentin/Software/StreamDeck-AudioSwitcher/build/_deps/streamdecksdk-src/StreamDeckSDK/ESDUtilities.h:22:27: error: 
      'path' is unavailable: introduced in macOS 10.15
  static std::filesystem::path GetPluginDirectoryPath();
```

My guess is that you are now shipping a binary that tries to link symbols that don't exist on macOS 10.14 or earlier.

I just filed https://github.com/fredemmott/StreamDeck-CPPSDK/issues/9 for the SDK, but in the mean time I think you should probably revert to a previous version of the SDK.

**To Reproduce**
1. Install the latest version of the plugin
2. Press a button assigned to the plugin

**Expected behavior**
Audio devices switch like they used to

Instead, you just get the ! error icon. Also, the property inspector is blank.

**Debugging Information**

Property inspector is blank

**Log File**
Attach (or copy-paste to gist.github.com) the debug log file (new).

There is no generated log file; StreamDeck0.log contains

```
13:21:21.2231          auto ESDCustomPlugin::StartPlugin(): Restarting plugin 'Audio Switcher' after one minute
13:21:21.3087          auto ESDCustomPlugin::StartPlugin(): The plugin 'Audio Switcher' crashed with code 6
```

** Operating System **

macOS 10.14 Mojave

**Additional context**

**Comment by fredemmott** [comment]
I'll ask elgato to push an update changing the minimum version to 10.15 for this plugin; old versions can be downloaded here: https://github.com/fredemmott/StreamDeck-AudioSwitcher/releases

I missed this as using a newer SDK with 10.14 as the target version works fine. As this is a hobby project, I am unable to build/test with multiple OS versions, so can't aim to support them.

**Comment by quentinmit** [comment]
It looks like the diff might be fairly small, so I'm going to try to send a PR to the SDK repo to fix the build.

FWIW I think you'll find 10.14 is still fairly common amongst Stream Deck users; it's the last macOS that supports 32-bit binaries, so 10.14 is needed to play a large swath of the Steam catalog on a Mac.

**Comment by fredemmott** [comment]
It's worth noting that while Apple do not appear to officially announce end of support for MacOS versions, it's widely believed that Apple's support for Mojave ended last year; for example, https://nvd.nist.gov/vuln/detail/CVE-2021-30919 allows opening a PDF file to take over your computer, and was only fixed in Catalina and above, while Mojave is known to be vulnerable to it.

**Comment by fredemmott** [comment]
> It looks like the diff might be fairly small, so I'm going to try to send a PR to the SDK repo to fix the build.

If this is something along the lines of statically linking the required parts of the C++ standard library, that'd be great; I won't be taking patches that remove use of `std::filesystem` though.

I've made a new release with an updated manifest, and reached out to Elgato to update/downgrade the store.

**Comment by quentinmit** [comment]
I sent https://github.com/fredemmott/StreamDeck-CPPSDK/pull/10

There's a single-header polyfill to add support for `std::filesystem` on older standard libraries.

**Comment by fredemmott** [comment]
@quentinmit thanks - could you give [RelWithDebInfo-StreamDeckPlugin](https://github.com/fredemmott/StreamDeck-AudioSwitcher/suites/7902456548/artifacts/336127699) a try?

**Comment by quentinmit** [comment]
> @quentinmit thanks - could you give [RelWithDebInfo-StreamDeckPlugin](https://github.com/fredemmott/StreamDeck-AudioSwitcher/suites/7902456548/artifacts/336127699) a try?

That build installs and runs correctly on macOS 10.14, thanks!

**Comment by fredemmott** [comment]
https://github.com/fredemmott/StreamDeck-AudioSwitcher/releases/tag/v3.1.2
